In [8]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup
import re
import os 
import googlemaps
import re
import numpy as np

In [9]:
#using request to scrape the area coe
url = 'http://www.weather.gov.sg/climate-historical-daily/'
res = requests.get(url)
content = res.text
soup = BeautifulSoup(content,'html.parser')

In [10]:
area = []
location = soup.find(class_="dropdown-menu long-dropdown").find_all('li')
for item in location:
    info = {}
    loc = item.a.text
    a = re.findall('\d+',str(item))
    area_code = 'S'+str(a[0])
    info[loc] = area_code
    area.append(info)
print(area)

[{'Admiralty': 'S104'}, {'Admiralty West': 'S105'}, {'Ang Mo Kio': 'S109'}, {'Boon Lay (East)': 'S86'}, {'Boon Lay (West)': 'S63'}, {'Botanic Garden': 'S120'}, {'Buangkok': 'S55'}, {'Bukit Panjang': 'S64'}, {'Bukit Timah': 'S90'}, {'Buona Vista': 'S92'}, {'Chai Chee': 'S61'}, {'Changi': 'S24'}, {'Choa Chu Kang (Central)': 'S114'}, {'Choa Chu Kang (South)': 'S121'}, {'Choa Chu Kang (West)': 'S11'}, {'Clementi': 'S50'}, {'Dhoby Ghaut': 'S118'}, {'East Coast Parkway': 'S107'}, {'Jurong (East)': 'S39'}, {'Jurong (North)': 'S101'}, {'Jurong (West)': 'S44'}, {'Jurong Island': 'S117'}, {'Jurong Pier': 'S33'}, {'Kampong Bahru': 'S31'}, {'Kent Ridge': 'S71'}, {'Khatib': 'S122'}, {'Kranji Reservoir': 'S66'}, {'Lim Chu Kang': 'S112'}, {'Lower Peirce Reservoir': 'S08'}, {'Macritchie Reservoir': 'S07'}, {'Mandai': 'S40'}, {'Marina Barrage': 'S108'}, {'Marine Parade': 'S113'}, {'Newton': 'S111'}, {'Nicoll Highway': 'S119'}, {'Pasir Panjang': 'S116'}, {'Pasir Ris (Central)': 'S94'}, {'Pasir Ris (West)': 'S29'}, {'Paya Lebar': 'S06'}, {'Pulau Ubin': 'S106'}, {'Punggol': 'S81'}, {'Queenstown': 'S77'}, {'Seletar': 'S25'}, {'Semakau Island': 'S102'}, {'Sembawang': 'S80'}, {'Sentosa Island': 'S60'}, {'Serangoon': 'S36'}, {'Serangoon North': 'S110'}, {'Simei': 'S84'}, {'Somerset (Road)': 'S79'}, {'Tai Seng': 'S43'}, {'Tanjong Katong': 'S78'}, {'Tanjong Pagar': 'S72'}, {'Tengah': 'S23'}, {'Toa Payoh': 'S88'}, {'Tuas': 'S89'}, {'Tuas South': 'S115'}, {'Tuas West': 'S82'}, {'Ulu Pandan': 'S35'}, {'Upper Peirce Reservoir': 'S69'}, {'Upper Thomson': 'S46'}, {'Whampoa': 'S123'}, {'Yishun': 'S91'}]

In [11]:
urls = []
months = ['01','02','03','04','05','06','07','08','09','10','11','12']
years = ['2016','2017','2018','2019']
for year in years:
    for month in months:
        for i in area:
            code = (list(i.values())[0])
            url_generator = "http://www.weather.gov.sg/files/dailydata/DAILYDATA_" + str(code) + "_" + year + month + ".csv"
            urls.append(url_generator)

In [12]:
requests.get(urls[0])
df = pd.read_csv(urls[0],encoding='ISO-8859-1')
df.head()

,Station,Year,Month,Day,Daily Rainfall Total (mm),Highest 30 Min Rainfall (mm),Highest 60 Min Rainfall (mm),Highest 120 Min Rainfall (mm),Mean Temperature (°C),Maximum Temperature (°C),Minimum Temperature (°C),Mean Wind Speed (km/h),Max Wind Speed (km/h)
0,Admiralty,2016,1,1,10.4,5.4,6.2,6.8,26.6,28.5,24.5,10.1,41.8
1,Admiralty,2016,1,2,13.0,9.2,11.0,11.2,25.7,27.9,23.1,7.9,49.3
2,Admiralty,2016,1,3,0.2,0.2,0.2,0.2,25.8,26.7,25.3,7.9,28.4
3,Admiralty,2016,1,4,0.4,0.2,0.4,0.4,27.6,31.1,25.2,11.2,34.2
4,Admiralty,2016,1,5,0.0,0.0,0.0,0.0,28.3,31.9,25.8,12.6,34.6

In [21]:
df = []
error = []
for url in urls:
    requests.get(url)
    try:
        df_new = pd.read_csv(url,encoding = 'ISO-8859-1')
        df.append(df_new)
    except:
        pass
final_df = pd.concat(df)

### There is some with station

In [23]:
final_df.tail()

,Station,Year,Month,Day,Daily Rainfall Total (mm),Highest 30 Min Rainfall (mm),Highest 60 Min Rainfall (mm),Highest 120 Min Rainfall (mm),Mean Temperature (°C),Maximum Temperature (°C),Minimum Temperature (°C),Mean Wind Speed (km/h),Max Wind Speed (km/h)
25,Ang Mo Kio,2018,6,26,9.4,3.4,4,6.8,26.5,27.9,23.6,4,23.8
26,Ang Mo Kio,2018,6,27,8,4.2,5,5,25.5,27.1,23.8,4.3,32.4
27,Ang Mo Kio,2018,6,28,0,0,0,0,27.9,31.6,24.9,5,24.8
28,Ang Mo Kio,2018,6,29,73.6,35.8,46.4,67.8,25.8,27.5,22.1,4,22.7
29,Ang Mo Kio,2018,6,30,0,0,0,0,27.8,30.6,25.4,5,20.9

In [24]:
final_df.shape

(61, 13)

In [25]:
final_df.to_csv('../data/weather_data_2015_2020.csv')

### getting latitude and longitude

In [27]:
api_key = 'AIgmaps = googlemaps.Client(key=api_key)

In [28]:
station_list = final_df['Station'].unique()

In [29]:
for station in station_list:
    try:
        geocode = gmaps.geocode(station)[0]['geometry']['location']

    except:
        geocode = {'lat':None,'lng':None}
    final_df.loc[final_df['Station']==station,'lat'] = geocode['lat']
    final_df.loc[final_df['Station']==station,'lng'] = geocode['lng']

In [30]:
final_df.tail()

,Station,Year,Month,Day,Daily Rainfall Total (mm),Highest 30 Min Rainfall (mm),Highest 60 Min Rainfall (mm),Highest 120 Min Rainfall (mm),Mean Temperature (°C),Maximum Temperature (°C),Minimum Temperature (°C),Mean Wind Speed (km/h),Max Wind Speed (km/h),lat,lng
25,Ang Mo Kio,2018,6,26,9.4,3.4,4,6.8,26.5,27.9,23.6,4,23.8,1.369115,103.845434
26,Ang Mo Kio,2018,6,27,8,4.2,5,5,25.5,27.1,23.8,4.3,32.4,1.369115,103.845434
27,Ang Mo Kio,2018,6,28,0,0,0,0,27.9,31.6,24.9,5,24.8,1.369115,103.845434
28,Ang Mo Kio,2018,6,29,73.6,35.8,46.4,67.8,25.8,27.5,22.1,4,22.7,1.369115,103.845434
29,Ang Mo Kio,2018,6,30,0,0,0,0,27.8,30.6,25.4,5,20.9,1.369115,103.845434